import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./compornents/Header";
import { adventPro, libreBaskerville, notoJP, monomaniac } from "./utiles/font";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${adventPro.variable} ${monomaniac.variable}`}>
      <body className="bg-white {inter.className}">{children}</body>
    </html>
  );
}
